[package]
name = "slog_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
slog = "2.7.0"
slog-async = "2.7.0"
slog-json = "2.6.1"
