refresh_rate: 5 seconds

root:
  level: error
  appenders:
    - stdout
appenders:
  stdout:
    kind: console
  my_lib_append:
    kind: file
    path: "log/my_lib.log"
    encoder:
      pattern: "{id} - {m}{n}"

loggers:
  my_lib:
    level: debug
    appenders:
      - my_lib_append
