/* automatically generated by rust-bindgen */

pub type wchar_t = ::std::os::raw::c_int;
pub type max_align_t = f64;
extern "C" {
    #[link_name = "\u{1}_levenshtein"]
    pub fn levenshtein(a: *const ::std::os::raw::c_char, b: *const ::std::os::raw::c_char)
        -> usize;
}
extern "C" {
    #[link_name = "\u{1}_levenshtein_n"]
    pub fn levenshtein_n(
        a: *const ::std::os::raw::c_char,
        length: usize,
        b: *const ::std::os::raw::c_char,
        bLength: usize,
    ) -> usize;
}
