[package]
name = "into_map_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
into_map = { path = "into_map" }
into_map_derive = { path = "into_map_derive" }
